# Generated by Django 3.1.7 on 2021-05-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='funcao_jogador',
            field=models.CharField(choices=[('Capitão', 'Capitão'), ('AWP', 'Awper'), ('Entry fragger', 'Entry fragger'), ('Suporte', 'Suporte'), ('Lurker', 'Lurker')], default='', max_length=20, verbose_name='Funçao'),
        ),
    ]
