# Generated by Django 3.1.7 on 2021-05-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_user_funcao_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='equipe_jogador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipe'),
        ),
    ]
