# Generated by Django 3.1.7 on 2021-05-26 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210525_2154'),
        ('users', '0003_user_equipe_jogador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='equipe_jogador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipe'),
        ),
    ]
