# Generated by Django 3.1.7 on 2021-05-12 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('senha', models.CharField(max_length=25, verbose_name='Senha')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('numeroMembros', models.IntegerField(blank=True, verbose_name='Numero de membros')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dono', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('Capitão', 'Capitão'), ('AWP', 'Awper'), ('Entry fragger', 'Entry fragger'), ('Suporte', 'Suporte'), ('Lurker', 'Lurker')], max_length=20, verbose_name='Funçao')),
            ],
            options={
                'verbose_name': 'Funcao',
                'verbose_name_plural': 'Funcoes',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ip', models.CharField(max_length=100, verbose_name='Ip ')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(choices=[('Capitão', 'Vaga para Capitão'), ('AWP', 'Vaga para Awper'), ('Entry Fragger', 'Vaga para Entry fragger'), ('Suporte', 'Vaga para  Suporte'), ('Lurker', 'Vaga para Lurker')], max_length=50, verbose_name='Vaga')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('equipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.equipe')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Funcoes', to='core.funcao')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=100, verbose_name='Nome')),
                ('dataInicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de inicio')),
                ('dataTermino', models.DateTimeField(blank=True, null=True, verbose_name='Data de termino')),
                ('informacao', models.TextField(blank=True, verbose_name='Informação')),
                ('situacaoEvento', models.CharField(max_length=30, verbose_name='Situação')),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
    ]
