# Generated by Django 3.1.7 on 2021-05-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='nivel_habilidade',
            field=models.CharField(blank=True, choices=[('Iniciante', 'Iniciante'), ('Amador', 'Amador'), ('Semi Profissional', 'Semi Profissional'), ('Profissional', 'Profissional')], max_length=17, verbose_name='Nivel de Habilidade'),
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Inicio')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Data de Termino')),
                ('premiacao', models.TextField(blank=True)),
                ('equipes_inscritas', models.ManyToManyField(blank=True, to='core.Equipe')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
            },
        ),
    ]
