# Generated by Django 3.1.7 on 2021-05-26 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210513_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipe'),
        ),
    ]
