# Generated by Django 3.1.7 on 2021-05-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210525_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='numeroMembros',
        ),
    ]
