# Generated by Django 3.1.7 on 2021-05-30 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_remove_equipe_numeromembros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('dataNasc', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('situacao', models.CharField(max_length=50, verbose_name='Situação')),
                ('nickname', models.CharField(max_length=25, verbose_name='Nickname')),
                ('patente', models.CharField(choices=[('Prata 1', 'Prata 1'), ('Prata 2', 'Prata 2'), ('Prata 3', 'Prata 3'), ('Prata 4', 'Prata 4'), ('Prata de Elite', 'Prata de Elite'), ('Prata de Elite Mester', 'Prata de Elite Mester'), ('Ouro 1', 'Ouro 1'), ('Ouro 2', 'Ouro 2'), ('Ouro 3', 'Ouro 3'), ('Ouro Mestre', 'Ouro Mestre'), ('AK 1', 'AK 1'), ('AK 2', 'AK1'), ('AK Cruzada', 'AK Cruzada'), ('Xerife', 'Xerife'), ('Águia 1', 'Águia 1'), ('Águia 2', 'Águia 2'), ('Supremo', 'Supremo'), ('Global', 'Global'), ('Sem Patente', 'Sem Patente'), ('Expirado', 'Expirado')], max_length=25, verbose_name='Patente')),
                ('nivelHabilidade', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Amador', 'Amador'), ('Semi Profissional', 'Semi Profissional'), ('Profissional', 'Profissional')], max_length=17, verbose_name='Nivel de Habilidade')),
                ('steam', models.CharField(max_length=200, verbose_name='Steam Url')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
